acs: 'YES'
code: WD_KCESS_R
comment: Changed from WD_KCOEN_R in 2024
department: Computing and Mathematics
dirty: false
full title: MSc in Computer Science (Enterprise Software Systems)
group: Computing and Mathematics
handbook: 'YES'
leader: Jimmy McGibney and Richard Frisby
level: 9
level 7 special exit full title: No level 7 special award for MSc in Computer Science
  (Enterprise Software Systems)
modes: P
name: MSc in Computer Science (Enterprise Software Systems)
num stages: 1
semesters:
  0: 1
  3: 1
short title: MSc in Computer Science (Enterprise Software Systems)
specialisation: Computer Science (Enterprise Software Systems)
stages:
  1:
  - 0
  - 3
type: MSc
volume3: 'YES'
